apiVersion: v1
kind: Service

metadata:
  name: nginx-service
  annotations:
    # Change internal to internet-facing
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

spec:
  selector:
    app: nginx

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer
